---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: src/contents
  label: Posts
  create: all
  match: "**/*.md"
  templates:
  - blog-post
upload_dir: public/assets/img/uploads
public_path: "/assets/img/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":year:-:month:-:day:-:filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:18
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn run build
