name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build assets
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: yarn install
      - run: yarn run build
